name: Build Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: 'Read Version'
        id: package_version
        run: jq .version package.json
      - name: 'Setup Font Awesome Registry'
        run: cp .github/.npmrc ~/.npmrc; sed -i 's/FONT_AWESOME_KEY/${{ secrets.FONT_AWESOME_KEY }}/g' ~/.npmrc
      - name: 'Install Dependencies'
        run: yarn install
      - name: 'Build Extension'
        run: yarn run build
      - name: 'Update Manifest Version'
        run: sed 's/0.0.0-alpha/${{ package_version }}/g build/manifest.json'
      - name: 'Package Extension'
        run: yarn run package
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: jira-launcher
          path: jira-launcher.zip
          retention-days: 3